language: elixir
elixir:
  - 1.6
script:
  - mix dialyzer --halt-exit-status
  - MIX_ENV=test mix coveralls.travis
notifications:
  recipients:
    - joel@vorce.se
cache:
  directories:
    - priv/plts